[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = [
    "@prisma/client", 
    "langchain", 
    "@langchain/textsplitters",
    "p-limit"
  ]

# Specific configuration for the process-meeting-background function
[functions.process-meeting-background]
  background = true
  included_files = [
    # Include all necessary source files from lib directory
    "src/lib/**",
    
    # Include database connection and models
    "src/server/db.ts",
    "src/server/db/**",
    
    # Include Prisma schema and generated files
    "prisma/schema.prisma",
    "node_modules/.prisma/**",
    
    # Include configuration files
    "package.json",
    ".env",
    ".env.production"
  ]